name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: TidyQuest Version
      description: Which version are you running?
      options:
        - v0.1.0
        - main (latest)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      options:
        - Docker Compose
        - Docker (manual)
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Provide details about your environment:
        - OS (Linux, macOS, Windows)
        - Docker version
        - Browser (if frontend issue)
      placeholder: |
        - OS: Ubuntu 22.04
        - Docker: 24.0.5
        - Browser: Chrome 120
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs (if any)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have reviewed the SECURITY.md file
          required: false
        - label: This is not a security vulnerability (if it is, please email instead)
          required: true
